version: '3'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: lab_user
      POSTGRES_PASSWORD: lab_password
      POSTGRES_DB: lab_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U lab_user" ]
      interval: 5s
      timeout: 3s
      retries: 5

  lab3:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: "10001"
      DATABASE_URL: "postgresql://lab_user:lab_password@db:5432/lab_db"
      JWT_SECRET_KEY: ""
    ports:
      - "10001:10001"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: